create_vscode_settings = True
run_after_build        = True
proj_name              = "1g engine"
proj_version           = "0.1.0.0"
file_name              = "1g"
compiler               = "gcc"
linker                 = "gcc"
flags                  = ['-Wall','-Wextra','-O3']
compiler_flags         = []
linker_flags           = []
output_path            = "bin"
source_path            = "src"
libs                   = []
pkgconf_libs           = ["SDL3"]
lib_paths              = []
include_paths          = []